[package]
name = "messages"
version = "0.1.0"
edition = "2021"

[dependencies]
der = { version = "0.7.9", features = ["alloc", "derive"] }
serde = { version = "1.0.204", features = ["derive"] }
convertible_derive = { path = "../macros/convertible_derive" } 