[package]
name = "kerberos"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
derive_builder = "0.20.1"
messages = { path = "../messages" }
rand = "0.8.5"
async-trait = "0.1.82"

[dev-dependencies]
tokio = { version = "1.0.1", features = ["full"] }
lazy_static = "1.5.0"