[package]
name = "kerberos-infra"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.11"
async-trait = "0.1"

[dev-dependencies]
mockito = "1.5.0"

[features]
default = ["tcp"]
tcp = []
udp = []