[package]
name = "kerberos-infra"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.11"
async-trait = "0.1"

[dev-dependencies]
rand = "0.8.5"

[features]
default = ["tcp", "udp"]
tcp = []
udp = []