postgres:
 host: "127.0.0.1"
 port: 5455
 username: "postgres"
 password: "password"
 name: "kerberos"
host:
 protocol: "tcp" # or "udp"
 as_port: 1088
 tgs_port: 1089
 host: "127.0.0.1"
cache:
 capacity: 1000
 ttl: 3600 # in seconds