name: Kerberos Simple

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '00 14 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: moonrepo/setup-rust@v1
        with:
          cache-base: main
          components: clippy
          bins: cargo-nextest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo build on messages crate
        working-directory: messages
        run: |
          cargo build --release --workspace --all --tests --benches

      - name: Run cargo nextest on messages crate
        working-directory: messages
        run: cargo nextest run --release --workspace

      - name: Run cargo build on kerberos-infra crate
        working-directory: kerberos-infra
        run: |
          cargo build --release --workspace --all --tests --benches

      - name: Run cargo nextest on kerberos-infra crate
        working-directory: kerberos-infra
        run: cargo nextest run --release --workspace -j 1