name: Kerberos Simple

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: moonrepo/setup-rust@v1
        with:
          cache-base: main
          components: clippy
          bins: cargo-nextest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run cargo clippy
        run: cargo clippy --workspace --tests --benches -- -D warnings
        
      - name: Run cargo build
        run: cargo build --release --workspace --all --tests --benches
        
      - name: Run cargo nextest
        run: cargo nextest run --release --workspace
